# markdown adn highlighter
markdown:    kramdown
highlighter: rouge

# permalinks
permalink:  pretty

# Server
url:        lukalafaye.github.io
baseurl:    /SafeSync
title:      SafeSync

# Custom variables
version:    v1.0.0

repo:       https://github.com/lukalafaye/SafeSync
download:   https://github.com/lukalafaye/SafeSync

docs:       https://github.com/lukalafaye/SafeSync/wiki
stargazers: https://github.com/lukalafaye/SafeSync/stargazers

author:
    github:   https://github.com/lukalafaye
